#Generated by Fabric Compiler ( version 2022.2-SP3 <build 127103> ) at Wed Aug 16 21:45:46 2023

add_design "D:/pango_work/image_process/txt_sim/src/binaryzation.v"
add_simulation "D:/pango_work/image_process/txt_sim/sim/file_sim_T0.v"
add_simulation "D:/pango_work/image_process/txt_sim/src/binaryzation.v"
