# ----------------------------------------
# Created on: Wed Oct 25 12:28:08 2023
# Auto generated by Pango
# ----------------------------------------

vlib  work
vmap  work ./work
vmap  usim "C:/pango/PDS_2022.2-SP3/pds_sim_library/usim"
vmap  adc "C:/pango/PDS_2022.2-SP3/pds_sim_library/adc"
vmap  ddrc "C:/pango/PDS_2022.2-SP3/pds_sim_library/ddrc"
vmap  ddrphy "C:/pango/PDS_2022.2-SP3/pds_sim_library/ddrphy"
vmap  hsst_e2 "C:/pango/PDS_2022.2-SP3/pds_sim_library/hsst_e2"
vmap  iolhr_dft "C:/pango/PDS_2022.2-SP3/pds_sim_library/iolhr_dft"
vmap  ipal_e1 "C:/pango/PDS_2022.2-SP3/pds_sim_library/ipal_e1"
vmap  pciegen2 "C:/pango/PDS_2022.2-SP3/pds_sim_library/pciegen2"
vlog -work work   \
"D:/Github/PDS_Sim_Binaryzation/Sim_Binaryzation/src/binaryzation.v" \
"D:/Github/PDS_Sim_Binaryzation/Sim_Binaryzation/sim/file_sim_T0.v" \
"D:/Github/PDS_Sim_Binaryzation/Sim_Binaryzation/src/binaryzation.v" 

# ----------------------------------------
